Gemfile
docs/services.md
lhs.gemspec
lib/lhs.rb
lib/lhs/concerns/service/endpoints.rb
lib/lhs/concerns/service/request.rb
lib/lhs/endpoint.rb
spec/endpoint/for_url_spec.rb
spec/service/endpoints_spec.rb
spec/service/includes_spec.rb
spec/support/cleanup_endpoints.rb

When using `includes` to include linked objects use known services for doing the request to be able to apply endpoint configurations from their service definitions (e.g. Auth).

Detect service from url

---

docs/services.md
lib/lhs/data.rb
spec/service/mapping_spec.rb

Simplifies mappings by evaluating them on the data instance itself.
That allow us to skip nasty parameter forwarding here.

Cleanup mappings

---

docs/services.md
lib/lhs/concerns/service/endpoints.rb
spec/collection/meta_data_spec.rb
spec/collection/without_object_items_spec.rb
spec/service/endpoint_options_spec.rb
spec/service/endpoints_spec.rb
spec/service/find_by_spec.rb
spec/service/find_spec.rb
spec/service/includes_spec.rb
spec/service/mapping_spec.rb

It was a bad idea to handle id as an implicit parameter.
It led to an issue where the id was passed as url parameter twice: https://github.com/local-ch/lhs/issues/33
So I decided to completely remove the implicit id handling and make it transparent.

No implicit id parameter handling anymore

---

lhs.gemspec
lib/lhs/concerns/record/includes.rb
spec/record/includes_spec.rb

`includes` was not duplicating a class so it was always hanging around.
The issue become visible when we changed the `create` behaviour.
It is fixed now

Fix includes

---

lib/lhs/concerns/record/all.rb
spec/record/all_spec.rb

It is not possible to spec requests like this when the method `all` is used inside controller:
```ruby
def index
@callcenters = Spamnumber.all(type: 'Verified', order_by: '-user_frequency', swiss_number: true)
end
```
```ruby
let(:callcenters) { [callcenter] }
before :each doe
stub_request(:get, %r{/spamnumbers}).to_return(body: callcenters.to_json)
end
```
Instead requests have to be stubbed like this:
```ruby
let(:callcenters) { { items: [callcenter], total: 1 } }
before :each doe
stub_request(:get, %r{/spamnumbers}).to_return(body: callcenters.to_json)
end
```
This error case is reproduced in the red specs from following spec-file:
```bash
rspec spec/record/all_spec.rb
```

reproduce errors in specs

---

README.md
lib/lhs/concerns/record/scope.rb
lib/lhs/concerns/record/where.rb
lib/lhs/record.rb
spec/record/scope_chains_spec.rb
spec/record/where_chains_spec.rb
spec/record/where_values_hash_spec.rb

**As lazy evaluated where statements can make tests fail in consuming application I will do a major version increase after merge**
Solves: https://github.com/local-ch/lhs/issues/103
LHS supports WhereChains. That allows you to chain multiple where-queries and helps you organizing query parameters that are used often in scopes (methods):
```ruby
class Record < LHS::Record
endpoint 'records/'
endpoint 'records/:id'
def self.blue
where(color: 'blue')
end
end
records = Record.blue.where(available: true)
...
records.where(visible: true).each do |record|
...
end
```
The example would fetch the following in the end: `{color: blue, available: true, visible: true}`.

+ where chains

---

README.md
lib/lhs/collection.rb
lib/lhs/concerns/data/equality.rb
lib/lhs/concerns/record/equality.rb
lib/lhs/data.rb
lib/lhs/item.rb
lib/lhs/record.rb
spec/data/equality_spec.rb
spec/data/is_item_or_collection_spec.rb
spec/data/parent_spec.rb
spec/record/equality_spec.rb

+ `collection?` to check if data is a collection
+ `item?` to check if data is an item
+ `parent` to navigate up
+ equality for data and record in order to make things comparable
! not bypassing data anymore when forwarding data from record to proxy
! keeping the special case for rubys native select (which has to be solved with delegation)

+ methods to navigate data

---

README.md
lib/lhs/concerns/record/all.rb
lib/lhs/concerns/record/batch.rb
lib/lhs/concerns/record/chainable.rb
lib/lhs/concerns/record/pagination.rb
lib/lhs/pagination.rb
spec/pagination/pages_left_spec.rb
spec/record/pagination_chain_spec.rb

You can use chainable pagination in combination with query chains:
```ruby
class Record < LHS::Record
endpoint 'http://local.ch/records'
end
Record.page(3).per(20).where(color: 'blue')
```
The applied pagination strategy depends on the actual configured pagination, so the interface is the same for all strategies:
```ruby
class Record < LHS::Record
endpoint 'http://local.ch/records'
configuration pagination_strategy: 'page'
end
Record.page(3).per(20).where(color: 'blue')
```
```ruby
class Record < LHS::Record
endpoint 'http://local.ch/records'
configuration pagination_strategy: 'start'
end
Record.page(3).per(20).where(color: 'blue')
```

Pagination chains

---

lib/lhs/concerns/record/chainable.rb
spec/record/immutable_chains_spec.rb

Always returns a new chain, so that the original is not getting mutated:
```ruby
blue_records = Record.where(color: 'blue')
blue_and_active_records = blue_records.where(active: true)
```

! immutable chains

---

README.md
lib/lhs/pagination.rb
spec/record/pagination_chain_spec.rb

Fixes cases where pagination arguments have been passed as strings
```
Record.page(params[:page])
```
Params are usually strings.

Fix pagination string case

---

lib/lhs/data.rb
spec/data/inspect_spec.rb

Data on the terminal now looks directly like raw data:
```ruby
data = Record.find(1)
data # { name: 'Steve' }
```
Before: 
```ruby
data
#<LHS::Data:0x007fe67a64f600 @_raw={:name=>\"Steve\"}, @_parent=nil, @_record=Record, @_proxy=#<LHS::Item:0x007fe67a64f420 @_data={:name=>\"Steve\"}, @_loaded=false>, @_request=nil, @_endpoint=nil>
```
On one hand this was leaking internals to the outside, second it makes people use `_raw` all over the place, but they shouldn't.
For internal reasons `inspect_without_focus` stays around.

! improve data inspect

---

lib/lhs/concerns/item/save.rb
spec/item/save_spec.rb

In the current implementation `save!` method always overwrites the headers passed via the options.
This PR fixes that misbehaviour.

Keep the headers passed via options to save

---

lib/lhs/concerns/item/validation.rb
spec/item/validation_spec.rb

LHS was taking the wrong endpoint when validating in the following case:
```ruby
class Recrod < LHS::Record
endpoint ':datastore/v2/records'
endpoint ':datastore/v2/records/:id', validates: 'publish'
end
```
```ruby
record = Record.find(1)
record.valid?
```
LHS took `:datastore/v2/records` as endpoint for validation even though the fetched record contained an embeded `href`. The reason it was not taking the correct endpoint was because the fetched record was containing the data for the paramter `id` itself. 
Injecting `{ href: 'http://datastore/v2/records/1', name: 'Test' }` into `:datastore/v2/records/:id` lead to an incomplete endpoint url as the record does not contain `id`.
This special case is fixed now, as parameters from embeded endpoints are extracted and taken into consideration …

! pick correct endpoint when validating and record contains embeded href

---

lib/lhs/concerns/record/request.rb
spec/record/includes_spec.rb

LHS was raising an exception when somebody tried to include empty collections.

! skip loading empty includes

---

lib/lhs/concerns/record/batch.rb
spec/record/find_in_batches_spec.rb

Bug Fix
LHS was not capable to do batch processing (internal pagination) when configured LHS::Record had custom pagination configuration (like items = 'docs', total = 'totalResults' etc.).
This fixes it and uses configured pagination to be applied when doing batch processing.

! batch processing with configured pagination

---

README.md
lhs.gemspec
lib/lhs/concerns/record/includes.rb
lib/lhs/concerns/record/request.rb
spec/record/includes_spec.rb

In case you want to forward options for the requests beeing made to fetch included/referenced resources:
```
Favorite.includes(:place).references(place: { auth: { bearer: '123' }})
```
Major version increase ahead, because of new ruby > 2.0.0 dependency.

Forward options to included/referenced resources

---

lib/lhs/concerns/record/includes.rb
lib/lhs/concerns/record/request.rb
spec/record/includes_spec.rb

In the following case, LHS was not expanding included resources:
```
Customer.includes(:places).find(1)
GET 'customers/1'
```
```
{
places: { href: 'customers/1/places' }
}
```
`includes` fetches places
```
GET 'customers/1/places'
{
items: [
{ href: 'datastore/places/1' },
{ href: 'datastore/places/2' },
{ href: 'datastore/places/3' }
]
}
```
but this just includes a list of links, so LHS was not further including the requested resources.
Now it does also fetch all those links in order to fulfil the requested: `Customer.includes(:places).find(1)`
Backwards compatible: Minor

Expand included collection items

---

README.md
lib/lhs/concerns/record/chainable.rb
lib/lhs/concerns/record/request.rb
spec/record/chain_error_handling_spec.rb
spec/record/includes_spec.rb

One benefit of chains is lazy evaluation. This means they get resolved when data is accessed. This makes it hard to catch errors with normal `rescue` blocks.
To simplify error handling with chains, you can also chain error handlers to be resolved, as part of the chain.
In case no matchin error handler is found the error gets re-raised.
```ruby
record = Record.where(color: 'blue')
.handle(LHC::BadRequest, ->(error){ show_error })
.handle(LHC::Unauthorized, ->(error){ authorize })
```
[List of possible error classes](https://github.com/local-ch/lhc/tree/master/lib/lhc/errors)

Error handling with chains

---

lib/lhs/record.rb
spec/record/create_spec.rb
spec/record/endpoint_misconfiguration_spec.rb
spec/record/inspect_spec.rb
spec/record/new_spec.rb

Consider following use case:
```ruby
class Feedback < LHS::Record
attr_accessor :listing
end
listing = Local::Listing(...)
f1 = Feedback.new(listing: listing)
f1._raw
=> { listing: listing }
f2 = Feedback.new.tap do |f|
f.listing = listing
end
f2._raw
=> {}
```
This PR fixes this issue.
The reason it occurred was that we had an assumption that everything that has a custom setter will end up in the raw data anyway, which is not always true (think instance variables).
It wouldn't be a big of an issue if not for the recursive data structures, which then cause stack overflow when trying to send them.

Do not store values set by custom setters in _raw by default

---

.rubocop.localch.yml
Gemfile
README.md
lhs.gemspec
lib/lhs/concerns/record/chainable.rb
lib/lhs/concerns/record/find.rb
lib/lhs/concerns/record/request.rb
lib/lhs/item.rb
spec/record/find_in_parallel_spec.rb

In case you want to fetch multiple records by id in parallel, you can also do this with `find`:
```ruby
Record.find(1, 2, 3)
```
If you want to inject values for the failing records, that might not have been found, you can inject values for them with error handlers:
```ruby
data = Record
.handle(LHC::Unauthorized, ->(response) { Record.new(name: 'unknown') })
.find(1, 2, 3)
data[1].name # 'unknown'
```

Find in parallel + Handle Errors (chained)

---

lib/lhs/item.rb
spec/collection/delegate_spec.rb
spec/collection/enumerable_spec.rb
spec/collection/respond_to_spec.rb
spec/data/collection_spec.rb
spec/item/respond_to_spec.rb
spec/item/setter_spec.rb

PATCH
```ruby
item.recommended = false
item.recommended # nil
```
```ruby
item.recommended = false
item.recommended # false
```

Fixes getters for false values

---

README.md
lib/lhs/concerns/record/chainable.rb
lib/lhs/concerns/record/destroy.rb
lib/lhs/record.rb
spec/record/destroy_spec.rb

MINOR
You can also destroy records directly without fetching them first:
```ruby
destroyed_record = Record.destroy('1z-5r1fkaj')
```
or with parameters:
```ruby
destroyed_records = Record.destroy(name: 'Steve')
```

Destroy records

---

lib/lhs/concerns/record/chainable.rb
spec/record/find_by_chains_spec.rb

```ruby
Record.options(auth: { bearer: access_token }).find_by!(name: 'Steve')
```
Chains resolves before `find_by!`, returns `nil` afterwards, as `find_by!` is not available on chains.
`find_by!` is available on chains and performs just like `Record.find_by!(args)`

+ missing find_by! to chains

---

.rubocop.yml
lib/lhs/concerns/item/save.rb
spec/item/save_spec.rb

Patch Version
```ruby
class RecordWithOptions < LHS::Record
endpoint 'http://datastore/records', headers: { 'X-Header' => 'VALUE' }
end
RecordWithOptions.save(some: 'thing')
```
It should merge endpoint headers to the request done saving the record.
It does not merge any endpoint options at all!

! merge endpoint options when saving

---

lib/lhs/errors.rb
spec/item/errors_spec.rb

PATCH VERSION
Context: validating business objects (create, update)
In case of a custom structure content in the response body of a error response, lhs was not storing any error messages in errors. So methods like `save`, `update` etc. have been returning the boolean indicating if save or updated succeeded, but asking the `errors` object on the specific instance was telling us the opposite: no error.
This could lead to inconsistent states.
In case of any LHC::Error the `errors` object returns and informs about errors.

There are errors

---

lib/lhs/concerns/item/save.rb
spec/record/save_spec.rb

PATCH VERSION
It was not able to compile urls for persistance through params. Everything had to be in the body, the items raw data, in order to have it available for endpoint selection and url compiling.
```ruby
class ContactPerson < LHS::Record
endpoint ':lcm/customers/:customer_id/contact_persons'
end
item = ContactPerson.new(name: 'Sebastian')
item.save(params: { customer_id: 123 })
```
The workaround before was to just store the data required for detecting and compiling the endpoint inside the item:
```ruby
item.customer_id = 123
item.save
```
But this requires that the particular endpoint has to ignore that data, as we are also sending it as part of the body. LCM does not, they are raising exceptions if data is send through the body, which is unknown, what is okay. But this lead to …

! save endpoint with compiled params

---

lib/lhs/concerns/record/chainable.rb
lib/lhs/concerns/record/find_by.rb
lib/lhs/concerns/record/request.rb
spec/record/find_by_chains_spec.rb
spec/record/includes_spec.rb

PATCH VERSION
A specific, complex `includes` and `references` case failed. One we had in SB:
```ruby
Place
.options(auth: { bearer: token })
.includes(contracts: :product)
.references(contracts: { auth: { bearer: token }, product: { auth: { bearer: token } } })
.find_by(id: online_entry_identifier)
```
Load place with auth token. Include contracts linked from place and the product, linked from any contract within place. Use auth token requesting place, contracts, and products.
Referencing deeper than one level failed (as you can see from the patch).
Referencing is forwarded properly, so we can authenticate requests made to data included over multiple levels.

! a more complex includes and references case

---

lib/lhs/concerns/record/request.rb
spec/record/includes_spec.rb

LHS was not expanding empty arrays. Wich turns out to be nil when accessing the nested data, instead of being an empty array, which would be actually more concrete.
```ruby
place = Place.includes(:contracts) # requesting contracts => { items: [] }
place.contracts # nil
```
```ruby
place.contracts
```

fix expanding empty arrays

---

lib/lhs/errors.rb
spec/item/errors_spec.rb

Validation  error messages that where unparsable where raising another problem, as `@messages` and `@message` was not when catching the error.

! parse error when body is unparsable

---

lib/lhs/concerns/item/save.rb
spec/item/errors_spec.rb

_PATCH VERSION_
```ruby
c = TelemarketingComplaint.new
c.save!
c.errors
c.save
c.errors
```
```ruby
c = TelemarketingComplaint.new
c.save!
c.errors
c.save
c.errors
```

! Parse errors on Record#save!

---

lib/lhs/concerns/item/validation.rb
spec/item/validation_spec.rb

When required parameters for validation url compilation have to be passed with local options, this was not working.
```ruby
class User < LHS::Record
endpoint 'http://datastore/v2/users/:user_id', validates: { params: { persist: false } }
end
user = User.build(email: 'steve@cloudy.com')
user.valid?(params: { user_id: 2 })
```
```ruby
user = User.build(email: 'steve@cloudy.com')
user.valid?(params: { user_id: 2 })
```

! validation url compiled with locally passed params

---

lib/lhs/concerns/item/save.rb
spec/record/create_spec.rb

When creating records, location header has not been considered when creation endpoint returns no content.
```ruby
contact_person = ContactPerson.create(first_name: 'Sebastian')
contact_person.href # nil
```
Location-Header is considered, fetched and merged with raw data if creation endpoint provides such header on creation.
```ruby
contact_person = ContactPerson.create(first_name: 'Sebastian')
contact_person.href # http://datastore/contact_persons/1
```

Load and merge created data through location header

---

.rubocop.yml
lib/lhs/concerns/record/request.rb
spec/record/includes_spec.rb
spec/record/references_spec.rb

It was not possible to apply the `references` options to all symbols of the `includes` array.
```ruby
options = { headers: { 'Authentication': 'Bearer 123' } }
customer = Customer
.includes(:electronic_addresses, :contact_addresses)
.references(
electronic_addresses: options,
contact_addresses: options
)
.find(1)
```
It was failing, because by mistake, the `references` hash was converted to an array internally, being applied only on the first symbol of the `includes` array.
The `references` hash, as expected, gets applied to all symbols in the `includes` array, according to their key: `:electronic_addresses` => `electronic_addresses: options`, etc.

Fix referencing options in case includes is an array of symbols

---

lib/lhs/concerns/record/endpoints.rb
lib/lhs/concerns/record/request.rb
spec/record/endpoints_spec.rb

It was not possible to include nested data, in case the Record definition was not containing a unique, parameterless base endpoint. Includes tried to finding parents base endpoint, even though urls are around, which led to the "Multiple Base Endpoints" exception. 
```ruby
class Contract < LHS::Record
endpoint ':datastore/contracts/:id'
endpoint ':datastore/entry/:entry_id/contracts'
end
Contract.includes(:product).where(entry_id: '123').all.first
```
It does not raise anymore, as base endpoints are not looked up anymore, as nested data contains the urls already.

Fix unique multiple endpoint bug, when including nested data

---

lib/lhs/concerns/record/request.rb
spec/record/includes_all_spec.rb

Fixes case where response contains empty array but LHS tries to access `._raw` on empty array.

Fix includes all for empty arrays

---

lib/lhs/concerns/record/request.rb
spec/record/includes_spec.rb

Including linked objects, when reference was an array of links was not working properly.
```ruby
{
category_relations: [
{ href: 'http://datastore/category/1' }, { href: 'http://datastore/category/2' }
]
}
```
```ruby
Place
.includes(:category_relations)
.find(1, 2)
```

+ test case for includes

---

lib/lhs/complex.rb
lib/lhs/concerns/record/request.rb
spec/complex/reduce_spec.rb
spec/record/includes_all_spec.rb

Including linked objects, when reference was an array partially with values and partially with hrefs, LHS failed.
```ruby
{
options: [
{ href: 'http://datastore/option/1' },
{ type: 'E_COMMERCE' }
]
}
```
```ruby
Place
.includes(:products)
.includes_all(:options)
.find(1)
```
Fixes a current problem in Customer Center:
https://rollbar.com/local.ch/ws-customer-center/items/1214/?item_page=0&#instances
https://rollbar.com/local.ch/ws-customer-center/items/1215/?item_page=0&#instances
LHS skips those items when including nested items.

! includes/includes all with fancy/weird arrays

---

lib/lhs/collection.rb
spec/collection/href_spec.rb

When querying with `where` and the server responds with `[]`, there is no `href` to use as an ID. This is a work-around for that case.

Allow empty array responses

---

README.md
lib/lhs/concerns/record/chainable.rb
lib/lhs/concerns/record/request.rb
spec/record/expanded_spec.rb

Some endpoints could respond a plain list of links without any expanded data. Like search endpoints.
If you want to have LHS expand those items, use `expanded` as part of a Query-Chain:
```json
{ 
"items" : [
{ "href" : "http://local.ch/customer/1/accounts/1" },
{ "href": "http://local.ch/customer/1/accounts/2" },
{ "href": "http://local.ch/customer/1/accounts/3" }
] 
}
end
```
```ruby
Account.where(customer_id: 123).expanded
```
You can also apply options to `expanded` in order to apply anything on the requests made to expand the links:
```ruby
Account.where(customer_id: 123).expanded(auth: { bearer: access_token })
```

Record.where(color: 'blue').expanded

---

README.md
lib/lhs/concerns/item/validation.rb
lib/lhs/errors.rb
spec/item/errors_spec.rb
spec/item/validation_spec.rb

Compatibility with ActiveModel
ActiveModel expects the errors object to always be present
!~ Introduce 'clear' on LHS::Error to mimic ActiveModel::Error behaviour

Compatibility with ActiveModel

---

.rubocop.localch.yml
lhs.gemspec
lib/lhs/concerns/proxy/accessors.rb
spec/data/item_spec.rb
spec/dummy/config/environments/test.rb

Java backends omit the seconds on ISO8601 times if they're `00`. The RegEx used to detect if it's a `Date` or `DateTime` did not take that into account and has been fixed.

Add missing seconds to regex for datetime detection

---

lib/lhs/concerns/record/model.rb
spec/record/persisted_spec.rb

*Patch version*
If the `href` attribute comes from a rails form, it will be `""` (an empty string) instead of nil. In that case, the record is still not persisted.

Consider records with an empty href not persisted

---

lhs.gemspec
lib/lhs/concerns/proxy/accessors.rb
lib/lhs/concerns/record/configuration.rb
lib/lhs/concerns/record/request.rb
spec/proxy/record_identification_spec.rb

This change fixes three issues. All three in combination lead to the problem, that a nested data collection was not recognized as such, as mentioned in https://github.com/local-ch/lhs/issues/215
(1) When accessing data, items/collections only have been distinguished by being either a hash or an array. I fixed/improved that, so that also hashes with an `items_key` get recognized as a collection when accessed.
(2) When a nested resource is linked, and this link contained get parameters, those get parameters have been dropped as part of making the link dynamically overloadable or parameters of the url , according to defined endpoint templates, exchangeable. Those preset get-paramters are now kept/preserved.
(3) When accessing a collection, the returned data does not have been …

Fix identifying records

---

README.md
lib/lhs/concerns/item/save.rb
lib/lhs/concerns/item/update.rb
lib/lhs/concerns/item/validation.rb
lib/lhs/concerns/proxy/errors.rb
lib/lhs/errors/base.rb
lib/lhs/proxy.rb
spec/item/translate_errors_spec.rb

*Minor Version*
Just like Activerecord, LHS tries to translate validation error messages.
If a translation exists for one of the following translation keys, LHS will take a translated error (also in the following order) rather than the plain error message/code:
```ruby
lhs.errors.records.customers.attributes.name.unsupported_property_value
lhs.errors.records.customers.unsupported_property_value
lhs.errors.messages.unsupported_property_value
lhs.errors.attributes.name.unsupported_property_value
lhs.errors.fallback_message
```

Validation errors translated by convention

---

lib/lhs/errors/base.rb
spec/item/errors_spec.rb

```
undefined method `model_name' for nil:NilClass
lhs (11.2.0) lib/lhs/errors/base.rb:88:in `find_translated_error_message'
lhs (11.2.0) lib/lhs/errors/base.rb:84:in `generate_message'
lhs (11.2.0) lib/lhs/errors/base.rb:35:in `set'
lhs (11.2.0) lib/lhs/errors/base.rb:41:in `[]'
```
Smooth as silk

Fix: There is no record for nested unknown data types

---

lhs.gemspec
lib/lhs/concerns/record/endpoints.rb
lib/lhs/concerns/record/request.rb
spec/record/includes_all_spec.rb

Problem:
```ruby
class Entry < LHS::Record
endpoint ':datastore/entry/v1/:id.json'
end
``` 
Records configured with host placeholders (see above) where raising URL.parsing exceptions, as they are per se not real urls by any standards.
Solution:
Computing urls from parameters when placeholders are detected, before the urls are actually parsed.

Fix url parsing for records using host placeholders

---

README.md
lib/lhs/errors/base.rb
spec/item/errors_spec.rb

*MINOR*
LHS provides the http status code received when performing validations on a record, through the errors object:
```ruby
record.save
record.errors.status_code #400
```

Adding error status codes to error object

---

lib/lhs/errors/base.rb
spec/item/errors_spec.rb

*PATCH*
When general error fallback message was configured, instead of return something `blank` when accessing errors, it was returning the general error message itself, which is an unwanted behaviour (bug).
Fixed with this patch.

Fix error accessor when general fallback error is configured

---

lib/lhs/collection.rb
lib/lhs/concerns/record/request.rb
spec/record/includes_all_spec.rb
spec/record/includes_spec.rb

*PATCH*
Imagine you work with places, and a place has `category_relations`
```
{
id: 1,
category_relations: [ { href: 'http://datastore/category_relations/1' } ]
}
```
When multiple places have been requested, with including all their `category_relations`, places with an empty array of `category_relations` where messing up the order of extended data, which lead to weird merged state of the places objects in the end...
```
{
id: 1,
category_relations: [ { href: 'http://datastore/category_relations/1' } ]
}
{
id: 2,
category_relations: []
}
{
id: 3,
category_relations: [ { href: 'http://datastore/category_relations/2' }, { href: 'http://datastore/category_relations/3' } ]
}
```
Was creating a request object array looking like:
```
[ 
{ url: 'http://datastore/category_relations/1' },
nil,
{ …
```

Fix weird order for special `includes_all` case

---

lib/lhs/collection.rb
lib/lhs/concerns/collection/internal_collection.rb
spec/collection/accessors_spec.rb
spec/collection/to_ary_spec.rb

*PATCH*
Some versions of rails use `to_ary` on collections passed to collection renderers with render partial.
This leads to some problems in some of our applications passing LHS Collections to rails partial renderers.
This patch fixes that problem, by implementing [to_ary](https://apidock.com/rails/ActiveRecord/Base/to_ary)

+ to_ary for collection

---

lib/lhs/errors/base.rb
spec/item/add_error_spec.rb
spec/item/errors_spec.rb
spec/record/creation_failed_spec.rb

*PATCH*
Access error messages hash was not able with indifferent access.
I found out that there such an access in location app: e.g. https://github.com/local-ch/location-app/blob/test-lhs-autoload/app/views/restaurants_feedbacks/_review_form.html.haml#L13
This change makes accessing error messages possible also for indifferent access.

Fix error access with indifferent access

---

lib/lhs/concerns/record/endpoints.rb
lib/lhs/concerns/record/request.rb
spec/record/includes_all_spec.rb

_PATCH_
LHS was trying to pick an endpoint for the root Record when trying to parse an included record's href instead of a endpoint for the included record.

Fix Compilation Incomplete Error when using includes_all

---

lib/lhs/concerns/proxy/accessors.rb
spec/item/dig_spec.rb

_PATCH_
Fixes `.dig`.
Was not working with LHS Data.
e.g. `place.dig(:local_entry, :local_entry_id)`

Fix item.dig(:something)

---

README.md
lib/lhs/concerns/record/configuration.rb
lib/lhs/data.rb
spec/record/items_created_key_configuration_spec.rb

_MINOR_
Is based on https://github.com/local-ch/lhs/pull/235.
If record data after creation is nested in the response body, configure the record, so that it gets properly merged with the your record instance:
```
POST /businesses
response: {
business: {
id: 123
}
}
```
```ruby
class Business < LHS::Record
configuration item_created_key: [:response, :business]
endpoint 'http://uberall/businesses'
end
business = Business.create(name: 'localsearch')
business.id # 123
```

configure item_created_key

---

README.md
lib/lhs/concerns/item/becomes.rb
lib/lhs/item.rb
spec/item/becomes_spec.rb

_MINOR_
Based on [ActiveRecord's implementation](http://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-becomes), LHS implements `becomes`, too.
It's a way to convert records of a certain type A to another certain type B.
_NOTE: RPC-style actions, that are discouraged in REST anyway, are utilizable with this functionality, too. See the following example:_ 
```ruby
class Location < LHS::Record
endpoint 'http://sync/locations'
endpoint 'http://sync/locations/:id'
end
class Synchronization < LHS::Record
endpoint 'http://sync/locations/:id/sync'
end
location = Location.find(1)
synchronization = location.becomes(Synchronization)
synchronization.save!
```

Item#becomes

---

lib/lhs/proxy.rb
spec/record/reload_by_id_spec.rb

_PATCH_
Due to the fact that within localsearch we heavily rely on hrefs, `reload!` was not take in consideration to reload records by present id, wich can be necessary for other APIs, like uberall.

Proxy#reload! also with id

---

README.md
lib/lhs/concerns/record/chainable.rb
spec/record/fetch_spec.rb

_MINOR_
Implements: https://github.com/local-ch/lhs/issues/189
[ActiveRecords' fetch](https://github.com/rails/rails/blob/92703a9ea5d8b96f30e0b706b801c9185ef14f0e/activerecord/lib/active_record/type/type_map.rb#L17)
LHS Chains can be resolved with `fetch`, similiar to ActiveRecord:
```ruby
records = Record.where(color: 'blue').fetch
```

Adding Chain#fetch

---

lhs.gemspec
lib/lhs/concerns/data/to_hash.rb
lib/lhs/concerns/proxy/accessors.rb
lib/lhs/errors/base.rb
lib/lhs/item.rb

_PATCH_
LHC 6.3.0 introduces response bodies being `nil`, this has to be taken in account for some of LHS' edgecases.

Compatible with LHC 6.3.0

---

README.md
lib/lhs/concerns/record/request_cycle_cache/interceptor.rb
lib/lhs/config.rb
spec/request_cycle_cache/main_spec.rb
spec/support/request_cycle_cache.rb

_PATCH_
fixes: https://jira.localsearch.ch/browse/WEB-4155 by introducing a configurable cache for the request cycle cache interceptor. 
it will try to use a `ActiveSupport::Cache::MemoryStore` if defined

use a configurable cache store for the request cycle cache

---

README.md
lib/lhs/concerns/record/chainable.rb
lib/lhs/concerns/record/request.rb
spec/record/ignore_errors_spec.rb

Implements some feedback from @Averethel (crazy stuff)... https://github.com/local-ch/lhs/pull/244
Most important improvements is the ability to provide a list of ignored errors:
```ruby
Record
.ignore(LHC::Unauthorized, LHC::Forbidden)
.where(color: :blue)
```

Ignore errors improvements

---

lib/lhs/proxy.rb
spec/record/reload_spec.rb

_PATCH_
LHS was returning objects from type LHS::Item rather then the correct Record class on `reload!`.
Fixes: https://github.com/local-ch/lhs/issues/249
```ruby
record.reload! # LHS::Item
```
```ruby
record.reload! # LHS::Record
```

Reload returns instance of correct type now

---

README.md
lib/lhs/test/request_cycle_cache_helper.rb

_PATCH_
I noticed some weird test-fails on salesbutler (https://ci.local.ch/cider-ci/ui/workspace/jobs/6b3ac0dd-5c2e-481b-8761-000b512bf07a) after switching to the new implementation of RequestCycleCache. So I guess this is necessary?

add test-support for RequestCycleCache

---

lib/lhs/pagination/base.rb
spec/data/collection_spec.rb

_PATCH_
Provides count information 0 when there is no count information in the pagination.

! count on empty collections

---

README.md
lib/lhs/concerns/record/request.rb
lib/lhs/pagination/base.rb
lib/lhs/pagination/offset.rb
lib/lhs/pagination/page.rb
lib/lhs/pagination/start.rb
spec/record/all_spec.rb
spec/record/endpoints_spec.rb
spec/record/includes_all_spec.rb
spec/record/paginatable_collection_spec.rb

_MAJOR_
_Might break existing tests for paginated endpoints because offset is now, occasionally set_
**Be careful using methods for batch processing. They could result in a lot of HTTP requests!**
`all` fetches all records from the service by doing multiple requests and resolving endpoint pagination if necessary.
[...]
**In case an API does not provide pagination information (limit, offset and total), LHS keeps on loading pages when requesting `all` until the first empty page responds.**

Improve load all

---

README.md
lib/lhs/concerns/record/configuration.rb
lib/lhs/concerns/record/find.rb
lib/lhs/concerns/record/find_by.rb
lib/lhs/item.rb
spec/record/item_key_spec.rb

_MINOR_
`item_key` key used to unwrap the actuall object from within the response body.
[...]
```json
{
"response": {
"location": {
"id": 123
}
}
}
```
```ruby
class Location < LHS::Record
configuration item_key: [:response, :location]
end
location = Location.find(1)
location.id # 123
```

Unwrap single items within nested response body

---

README.md
lib/lhs/concerns/item/save.rb
lib/lhs/concerns/item/update.rb
lib/lhs/data.rb
spec/item/errors_spec.rb
spec/item/partial_update_spec.rb

_MINOR_
Often you just want to update a single attribute on an existing record. As ActiveRecord's `update_attribute` skips validation, which is unlikely with api services, and `update_attributes` is just an alias for `update`, LHS introduces `partial_update` for that matter.
`partial_update` will return false if persisting fails. `partial_update!` instead will an raise exception.
`partial_update` always updates the data of the local object first, before it tries to sync with an endpoint. So even if persisting fails, the local object is updated.
```ruby
record = Record.find('1z-5r1fkaj')
record.partial_update(recommended: false)
{
recommended: true
}
```

Partial update

---

README.md
lib/lhs/concerns/proxy/problems.rb
spec/item/access_errors_spec.rb

_PATCH_
Errors have not been accessible under certain circumstances. In general, when `field_errors` are part of `raw`, they should be accessible.
The fact that records could have errors is not coupled to any response status code.
LHS makes errors accessible, if they are present:
```
{
company_name: 'localsearch',
field_errors: [{
code: 'REQUIRED_PROPERTY_VALUE',
path: ['place', 'opening_hours']
}
}
```
LHS makes those errors available when accessing `.errors`:
```ruby
presence = Presence.create(
place: { href: 'http://storage/places/1' }
)
presence.errors.any? # true
presence.place.errors.messages[:opening_hours] # ['REQUIRED_PROPERTY_VALUE']
```

+ make errors available if there are some

---

lib/lhs/concerns/item/save.rb
lib/lhs/concerns/item/update.rb
lib/lhs/data.rb
lib/lhs/proxy.rb
spec/record/reload_spec.rb

_PATCH_
Fixes bug where a response with nested response data was nor merged during `reload!` (Uberall case).
- Also refactors unwrap

Fix reload merge

---

lib/lhs/concerns/record/request.rb
spec/record/endpoint_options_spec.rb

_PATCH_
When endpoints had configured headers and other head options has been passed either trough certain actions, like update (accept: 'application/json') or via chain options, they have been overwritten by a shallow merge of options.
Fix is to deep merge options when processing request options.

Deep merge options when processing request options

---

lib/lhs/problems/errors.rb
spec/item/nested_errors_spec.rb

_PATCH_
LHS was not capable to handle resources that contained resource and error data.
```
{
field_errors:[{code: 'REQUIRED_DATA', path: ['place]}]
}
```
```
{
place: { 'href': 'http://places/1' },
field_errors:[{code: 'REQUIRED_DATA', path: ['place]}]
}
```
Because nested data handling was passing response data while accessing nested data structures, it tried to access errors within the response body, with fails for certain data structures.
This makes LHS more smart about what inside the response actually are errors and whats not.

BUGFIX: Nested field error forwarding

---

.rubocop.yml
README.md
lib/lhs/problems/base.rb
lib/lhs/problems/errors.rb
lib/lhs/problems/warnings.rb
spec/item/error_codes_spec.rb
spec/item/errors_spec.rb
spec/item/warning_codes_spec.rb

_MINOR_
As `errors.messages` is already translated, it's inconvenient to have logic testing error codes.
Here we introduce `errors.codes` which always returns just the codes, so you can attach logic to it.
```ruby
user.errors.messages # {:email=>["Translated error message that this value is required"]}
user.errors.codes # {:email=>["REQUIRED_PROPERTY_VALUE"]}
```

Introducing errors.codes

---

.rubocop.yml
README.md
lib/lhs/concerns/data/becomes.rb
lib/lhs/concerns/proxy/accessors.rb
lib/lhs/concerns/record/relations.rb
lib/lhs/data.rb
lib/lhs/item.rb
lib/lhs/proxy.rb
lib/lhs/record.rb
lib/lhs/version.rb
spec/record/has_many_spec.rb
spec/support/cleanup.rb

_MINOR_
Even though, nested data is usually automatically casted when accessed, see: [Nested records](#nested-records), sometimes api's don't provide dedicated endpoints to retrieve these records.
As those records also don't have an href, nested records can not be casted automatically, when accessed.
Those kind of relations, you can still configure manually:
```ruby
class Location < LHS::Record
endpoint 'http://uberall/locations/:id'
has_many :listings
end
class Listing < LHS::Record
def supported?
type == 'SUPPORTED'
end
end
Location.find(1).listings.first.supported? # true
```

Record Relations: has_many

---

lib/lhs/concerns/data/becomes.rb
lib/lhs/version.rb
spec/record/has_many_spec.rb

_PATCH_
When casting data on access (becomes), the data hierarchy was not preserved.
```ruby
location.listings.first.parent # nil
```
``` ruby
location.listings.first.parent # listings
location.listings.first.parent.parent # location
```

Preserving Hierarchy Fix

---

lib/lhs/pagination/base.rb
lib/lhs/version.rb
spec/require_lhs_spec.rb

#PATCH
Issue: using `require 'lhs'` in a non rails app cause some issues with `delegate`.
`NoMethodError: undefined method `delegate' for LHS::Pagination::Base:Class`
This solves this specific use case.

Fix require lhs

---

lib/lhs/concerns/collection/internal_collection.rb
lib/lhs/version.rb
spec/collection/delegate_spec.rb

Give internalCollection a more array'y feel, by having it support `:compact`

Add :compact to Internal Collection

---

lib/lhs/collection.rb
lib/lhs/item.rb
lib/lhs/version.rb
spec/item/blacklisted_keywords_spec.rb

`exclude?` raises exceptions when used with none rails/activesupport applications.
Currently I've problems with `lcl`
```
/Users/Sebastian/.rvm/gems/ruby-2.4.1/gems/lhs-14.6.3/lib/lhs/item.rb:39:in `respond_to_missing?': undefined method `exclude?' for ["new", "proxy_association"]:Array (NoMethodError)
from /Users/Sebastian/.rvm/gems/ruby-2.4.1/gems/lhs-14.6.3/lib/lhs/data.rb:87:in `method_missing'
from /Users/Sebastian/.rvm/gems/ruby-2.4.1/gems/lhs-14.6.3/lib/lhs/record.rb:85:in `respond_to_missing?'
from /Users/Sebastian/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/core_ext/object/try.rb:6:in `respond_to?'
from /Users/Sebastian/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.4/lib/active_support/core_ext/object/try.rb:6:in `try'
from …
```

Fix exclude?

---

lib/lhs/concerns/proxy/accessors.rb
lib/lhs/version.rb
spec/item/fetch_spec.rb

_PATCH_
`.fetch` was not forwarded to raw for all lhs data (item) objects.
```
place = Place.find(123) # raw: {id: '123'}
place.fetch(:id) # nil
```
```
place = Place.find(123) # raw: {id: '123'}
place.fetch(:id) # 123
```

! fetch for data item

---

lib/lhs/concerns/record/batch.rb
lib/lhs/version.rb
spec/record/find_in_batches_spec.rb

This method could not deal with pagination and limit key names that were nested. This fixes that problem.

Fix find_in_batches

---

lhs.gemspec
lib/lhs/concerns/item/save.rb
lib/lhs/concerns/item/update.rb
lib/lhs/concerns/item/validation.rb
lib/lhs/version.rb
spec/record/options_spec.rb

_MINOR_
Makes LHS LHC 9 compatible.
See breaking change LHC 9: https://github.com/local-ch/lhc/releases/tag/v9.0.0
Basically: 
- Getting rid of calling `.to_json` everytime we provide a request body, as lhc takes care of formats
- Fix some test stubs

Make it LHC 9 compatible

---

lib/lhs/concerns/record/request.rb
lib/lhs/version.rb
spec/record/includes_all_spec.rb

Fixes an error with nested optional includes.
Suppose the following set of requests:
```
=> http://datastore/favorites
{
items: [{
href: "http://datastore/favorites/1",
place: {
href: "http://datastore/places/1"
}
}, {
href: "http://datastore/favorite/2",
place: {
href: "http://datastore/places/2"
}
}],
total: 2,
offset: 0,
limit: 100
}
```
```
=> http://datastore/places/1
{
href: "http://datastore/places/1",
name: 'Place 1',
contracts: {
href: "http://datastore/places/1/contracts"
}
}
```
```
=> http://datastore/places/1/contracts
{
items: [{
href: "http://datastore/places/1/contracts/1",
name: 'Contract 1'
}],
total: 1,
offset: 0,
limit: 10
}
```
```
=> http://datastore/places/2
{
href: "http://datastore/places/2",
name: 'Place 2'
}
```
Notice how `Place 2` does not have any contracts. …

! fix nested includes

---

lhs.gemspec
lib/lhs/version.rb

The LHC dependency was to strict.
This PR bumps to current LHC and only requires the MAJOR version as requirement.

Fix lhc dependency

---

lib/lhs/item.rb
lib/lhs/version.rb
spec/collection/to_ary_spec.rb
spec/data/to_ary_spec.rb

Some functions in Rails find out if an object is an Array (or Array-like) by checking if it responds to the method `to_ary`. Since LHS usually responds to _everything_, it returned true for that, but then returned `nil` for `to_ary`. This gave problems especially with `fields_for`.

Single items do not respond to to_ary

---

lib/lhs/record.rb
lib/lhs/version.rb
spec/record/to_ary_spec.rb

Quick fix to get `respond_to?(to_ary)` to work correctly for classes derived from `LHS::Record`.

to_ary for LHS::Record

---

lib/lhs/concerns/record/endpoints.rb
lib/lhs/version.rb
spec/record/endpoint_inheritance_spec.rb
spec/record/endpoint_misconfiguration_spec.rb

_MINOR_
The previous wording of "clashing" endpoints was rather imprecise. 
This PR switches the wording  to "ambiguous", which seems to be more precise and more common in software engineering.

Ambiguous not clashing

---

.rubocop.yml
README.md
lib/lhs/concerns/record/chainable.rb
lib/lhs/concerns/record/configuration.rb
lib/lhs/concerns/record/request.rb
lib/lhs/version.rb
spec/record/all_spec.rb
spec/record/fetch_spec.rb

Fixes: https://github.com/local-ch/lhs/issues/311
When requesting `all` for not paginated endpoints, it's trying to load all pages. If the endpoint is not paginated, LHS loads for ever, as it doesn't know when to stop. Now it shows a warning if it does so, as the behaviour is still desired, for endpoints, that do implement pagination, but do not provide pagination meta data as part of the response.
```ruby
Record.all
```
Fixes: https://github.com/local-ch/lhs/issues/312
In case your record endpoints are not implementing any pagination, configure it to be `paginated: false`. Pagination will not be performed automatically in those cases:
```ruby
class Record < LHS::Record
configuration paginated: false
end
```
```ruby
records = Record.all
```
```
GET https://service.example.com/records
``` …

Improve retrieving collections from unpaginated endpoints

---

lib/lhs/concerns/item/update.rb
lib/lhs/concerns/record/custom_setters.rb
lib/lhs/record.rb
spec/item/update_spec.rb

This PR enables LHS to apply custom setters on `update` commands. Previously they only have been applied to `new` and `create`.

Apply custom setters for update

---

lhs.gemspec
lib/lhs/version.rb

Projects using LHS can't update to LHC just yet. This version allows them to.

Bump version dependency to LHC 10

---

README.md
lib/lhs/concerns/record/batch.rb
lib/lhs/version.rb
spec/record/find_each_spec.rb

_MINOR_
This PR enables us to add more options than just params to the batch processing methods `find_each` and `find_in_batches`.

Allow Batch Processing Request Options

---

lib/lhs/concerns/proxy/accessors.rb
lib/lhs/version.rb
spec/record/has_one_spec.rb

The try to implement cache for relations.
Cache was not implemented directly in `LHS::Data::Becomes#becomes` because memoization will not work because we create a new instance of `LHS::Data` class every time we wrap a returned value (https://github.com/local-ch/lhs/compare/relation-cache?expand=1#diff-980515af88e289a4db6f934b06c27524R76).

Cache the relations.

---

lib/lhs/concerns/proxy/accessors.rb
lib/lhs/version.rb
spec/record/has_one_spec.rb

1. Clear cache to prevent the issues when the association(s) should be modified or at least not limit users:
```ruby
if user.comments.blank?
user.comments = [Comment.new]
end
```
this code might be used in the form builder to build associations.
2. If it's possible user relations hash to get the class for the instance. If don't do it, then when `href` param is given for the record the branching with cache will not be reachable and in order to cover with cache another case we need to use more complex key, maybe something like `[klass, value]` but i think that currently it's not necessary since we can achieve associations cache without it.

Clear cache when call setter method. If it's possible use relations hash to get the class and cache the instance in the first place.

---

lib/lhs/concerns/record/find.rb
lib/lhs/version.rb
spec/record/ignore_errors_spec.rb

_PATCH_
This PR fixes ignoring errors with find with parameters.
```ruby
Record.ignore(LHC::NotFound).find(id: 2)
```
Does not through exception but returns `nil` as expected.

Fix ignoring errors with find (with parameters)

---

Gemfile.activesupport4
lib/lhs/concerns/proxy/accessors.rb
lib/lhs/concerns/record/endpoints.rb
lib/lhs/data.rb
lib/lhs/version.rb
spec/item/update_spec.rb
spec/record/cast_nested_data_spec.rb

_MAJOR_
Applying nested record endpoint options was not working, because internally, always the options of the root record has been applied:
```ruby
class Account < LHS::Record
endpoint "https://datastore/accounts"
end
class CustomerRelation < LHS::Record
endpoint "https://datastore/accounts/{account_id}/customer-relations", auth: { bearer: '123' }
end
```
```ruby
new_account = Account.create(email: 'some@email.com')
```
```
POST https://datastore/accounts
{ customer_relations: { href: 'https://datastore/accounts/123/customer-relations' } }
```
```ruby
customer_relation = new_account.customer_relations
customer_relation.local_customer_id = '123'
customer_relation.save!
```
Was not applying the configured bearer token options on the records endpoint.
It does apply the records endpoint …

Fix applying nested records endpoint options

---

lib/lhs/concerns/proxy/accessors.rb
lib/lhs/concerns/record/request.rb
lib/lhs/version.rb
spec/record/has_many_spec.rb
spec/record/has_one_spec.rb
spec/record/relation_caching_spec.rb

LHS used to cache associated resources. This PR does clear this cache when new resources are included.
Before:
```ruby
class Place < LHS::Record
endpoint 'https://datastore/places/{id}'
has_many :available_assets
end
class AvailableAsset < LHS::Record
end
```
```ruby
place = Place
.options(auth: { bearer: 'XYZ' })
.includes_all(:available_assets)
.find(place_id)
place.available_assets.first
> nil
```
Now:
```ruby
place.available_assets.first
=> AvailableAsset https://datastore/places/4MTVj3Q8viP8645aU0eHSQ
> available_assets
:asset_code => "OPENING_HOURS"
```

Clear cache of associations when lhs includes new resources

---

lib/lhs/concerns/item/save.rb
lib/lhs/version.rb
spec/record/ignore_errors_spec.rb

_PATCH_
LHS was raising exceptions when `ignore` was used in combination with `create`.
e.g. 
```ruby
Record.ignore(LHC::Conflict).create(name: 'Steve')
```
This PR fixes that case.

Fix ignore errors in create cases

---

spec/record/has_many_spec.rb
spec/record/has_one_spec.rb

This PR adds tests that proof that explicit association configuration comes before href, when determine/casting a class (record) in LHS.

Association configuration

---

lib/lhs/concerns/item/endpoint_lookup.rb
lib/lhs/concerns/item/save.rb
lib/lhs/concerns/item/update.rb
lib/lhs/version.rb
spec/item/partial_update_spec.rb
spec/item/save_spec.rb
spec/item/update_spec.rb
spec/record/options_spec.rb

_MAJOR_
- Extract `url_for_persistance!` in a separate module used by `save`
- Use the new extracted method to lookup the endpoint for `update`
- Remove interpolated params from `data` and `options` when using `url_for_persistance!`
- This change also fixes update endpoint lookup using multiple placeholders

Endpoint with multiple placeholders

---

lib/lhs/concerns/record/request.rb
lib/lhs/version.rb
spec/record/includes_all_spec.rb

_PATCH_
LHS was raising:
```
Failure/Error: return if data.length.zero?
NoMethodError:
undefined method `zero?' for nil:NilClass
```
When you tried to include a collection (with `includes_all`) via a single item:
e.g.
```ruby
Place.includes_all(customer: addresses)
```
Now fixed.

Fixes includes_all trough single item

---

README.md

Documentation was wrong about what `create` returns.
It's aligned with how ActiveRecord works in regards of `create`. too.
https://github.com/rails/rails/blob/5bc494b35e4c8b91f33b517928e32ee6a6d1ec20/railties/lib/rails/application.rb#L100

Documentation about what create returns

---

lib/lhs/record.rb
lib/lhs/version.rb
spec/item/update_spec.rb
spec/record/dup_spec.rb

Override Object#dup because it doesn't support copying any singleton methods, which leads to missing `_data` method when you execute `dup`.

Override Object#dup.

---

lib/lhs/concerns/record/attribute_assignment.rb
lib/lhs/version.rb
spec/record/attribute_assignment_spec.rb

`assign_attributes` has been introduced as minor (non-breaking).
As this does not seem to be the case, this patch, removes the breaking part, leaves it up to @zhublik to either add it in a non breaking change (patch), or breaking one (major) afterwards, but for now, this PR patches the current version.

Remove attributes= for now

---

lib/lhs/item.rb
lib/lhs/version.rb
spec/record/item_key_spec.rb

```
class Location < LHS::Record
configuration item_key: [:response, :location]
endpoint 'http://uberall/location'
endpoint 'http://uberall/location/{id}'
end
```
A `LHS::Record` which configures a `item_key`.
We would lose associated information (like the _request object)
We preserve associated information (like the _request object)

Expose Header Information

---

README.md
lib/lhs.rb
lib/lhs/concerns/is_href.rb
lib/lhs/concerns/record/chainable.rb
lib/lhs/concerns/record/find.rb
lib/lhs/record.rb
lib/lhs/version.rb
spec/record/where_spec.rb

_MINOR_
While `find` was always able to fetch single records by provided href, `where` did not implement that functionality.
This PR adds the ability to pass an href to `where` and fetch a collection of records that way.
This is gonna be used in Customer Center for the user list, where we have to use `next` and `previous` links to navigate the user pagination.
You can also provide hrefs to fetch multiple records:
```ruby
Record.where('https://service.example.com/accociation/12345/records')
```
```
GET https://service.example.com/accociation/12345/records
```

Where with href

---

lib/lhs/concerns/record/request.rb
lib/lhs/version.rb
spec/option_blocks/main_spec.rb

When option blocks where used with making requests in parallel, the following exception was raised:
```
expected no Exception, got #<NoMethodError: undefined method `deep_merge' for #<Array:0x00007fea275239b0>> with backtrace:
```
Now fixed.

Fix raising exception when creating parallel requests

---

README.md
lib/lhs/concerns/record/href_for.rb
lib/lhs/record.rb
lib/lhs/version.rb
spec/record/href_for_spec.rb

_MINOR_
Sometimes you need to generate full hrefs/urls for records but you just have parameters that describe that record, like the ID.
For those usecases you can use `href_for(params)`:
```ruby
Presence.create(place: { href: Place.href_for(123) })
```
```
POST '/presences' { place: { href: "http://datastore/places/123" } }
```

Adding href_for

---

README.md
lib/lhs/rspec.rb
lib/lhs/version.rb

This follows the simple approach of loading a specific gems test helper in its entirety, instead of needing to know internals and individual test class files.
This is generally performed by a lot of standard gems out there, like webmock, capybara etc. and already has been introduced to LHC here: https://github.com/local-ch/lhc#testing
_MAJOR_
Replace 
```ruby
require 'lhs/test/request_cycle_cache_helper'
```
With:
```ruby
require 'lhs/rspec'
```

The simple lhs/rspec test helper approach

---

lib/lhs/rspec.rb
lib/lhs/test/stub.rb
lib/lhs/version.rb
spec/stubs/all_spec.rb

Unfortunately in an app, when loading lhs and rspec independently, rspec "patches" all objects/modules in the test context, and adds their own "stub" method to it, including the "LHS" namespace.
This PR shifts the LHS.stub definition to be initialized after rspec is done with messing around.
Unfortunately I didn't find a way to test that from within LHS 🤷‍♂

Fix rspec stub override

---

lib/lhs/concerns/option_blocks.rb
lib/lhs/interceptors/extended_rollbar/thread_registry.rb
lib/lhs/interceptors/request_cycle_cache/thread_registry.rb
lib/lhs/version.rb

in some constellation this dependency was not autoloaded anymore. make the require explicit.
I am not able to create the exact same scenario for a test. What I do know:
- `lcl` crashes with `uninitialized constant ActiveSupport::PerThreadRegistry (NameError)`
- this fix when applied to the locally used lhs, solved my issue
- I assume the issue starts happening when the application context uses rails 6. but i could not reproduce the error when using activesupport 6 in LHS, something else is amiss :-(

LHS require missing dependency

---

lib/lhs/concerns/record/request.rb
lib/lhs/version.rb
spec/record/includes_spec.rb

This enables us to load nested linked data, even if it has been nested in unlinked structures:
Upcoming place change:
```
{
"customer": {
"salesforce": {
"href": "https://salesforce/customers/1"
}
}
}
```
`customer` itself is not a linked resource on it's own, it's just another structure/namespace.
Previously LHS tried to load that namespace when you would instruct it to load the salesforce customer
```
Place.includes(customer: :salesforce).find(1)
```
Now LHS skips the namespace `customer` as it does not have an `href` and therefore does not need to be loaded.

Include nested data that's nested in structures

---

lib/lhs/concerns/record/request.rb
lib/lhs/version.rb
spec/record/includes_spec.rb

Implementing `handle_skip_include` here https://github.com/local-ch/lhs/pull/376/files#diff-ffbc06effcbee79e18771740f1ba521bR194 made nested includes of not existing data run into this issue/exception.
This patches the case where include is skipped, by preventing access of the none existing data.

prevent exception when including nested nothing

---

lib/lhs/concerns/record/request.rb
lib/lhs/version.rb
spec/record/includes_spec.rb

When including empty structures (see spec), LHS was raising an exception.

fix accessing empty structures

---

README.md
lib/lhs/concerns/record/request.rb
lib/lhs/interceptors/auto_oauth/interceptor.rb
lib/lhs/version.rb
spec/auto_oauth_spec.rb
spec/dummy/app/controllers/automatic_authentication_controller.rb
spec/dummy/app/models/dummy_record_with_auto_oauth_provider.rb
spec/dummy/app/models/providers/internal_services.rb
spec/dummy/config/routes.rb

While trying to implement auto oauth into the new localsearch app, I realized that providers have not been supported for auto oauth.
This PR changes this and adds auto oauth athentication for providers:
If you're using LHS service providers, you can also configure auto auth on a provider level:
```ruby
module Providers
class Localsearch < LHS::Record
provider(
oauth: true
)
end
end
```
or with multiple auth providers:
```ruby
module Providers
class Localsearch < LHS::Record
provider(
oauth: :provider_1
)
end
end
```

fix for providers

---

README.md
lib/lhs/concerns/record/update.rb
lib/lhs/record.rb
lib/lhs/version.rb
spec/record/update_spec.rb

This PR allows to directly update records when ID is already known.
```
Record.update(id: 1234, name: 'Steve')
```

Record.update

---

README.md
lhs.gemspec
lib/lhs/concerns/record/request.rb
lib/lhs/version.rb
spec/record/includes_first_page_spec.rb

MAJOR
LHS and LHC were meant to raise errors in case of unexpected network responses, like 404 (anything but 20X basically).
We had some trouble including nested linked resources in the new localsearch app when some of them were leading to a 404.
Because LHS was catching `LHC::NotFound` internally, it ,by accident, didn't include any resources at all, if there were loaded in batches/in parallel.
See: https://github.com/local-ch/lhs/pull/386/files#diff-ffbc06effcbee79e18771740f1ba521bL211
This PR changes the way LHS reacts in case of request errors while including nested resources. It does not skip them anymore, but raises them, which also allows people to control an includes behaviour for response issues while requesting the includes.
See: …

Fix auto expand included

---

README.md
lhs.gemspec
lib/lhs/concerns/record/chainable.rb
lib/lhs/concerns/record/request.rb
lib/lhs/version.rb
spec/dummy/app/controllers/error_handling_with_chains_controller.rb
spec/record/error_handling_spec.rb
spec/record/find_in_parallel_spec.rb
spec/record/handle_includes_errors_spec.rb
spec/record/includes_first_page_spec.rb

LHC renamed `ignored_errors` to `ignore` and `error_handler` to `rescue`.
This PR bumps LHC and changes internal naming of using those LHC actions/options.
This PR also renames `handle` to `rescue` and  to stick with the naming.
MAJOR

Ignore and rescue lhc

---

lib/lhs/concerns/record/request.rb
lib/lhs/version.rb
spec/record/compact_spec.rb
spec/record/includes_expanded_spec.rb
spec/record/references_spec.rb

There was wrong passing of `options` instead of `reference` deep inside some of the handle includes internal in cases includes where not pre expanded :atom: 🚀 .
This might accidentally passed `?limit=100` to some included requests, that you need to remove again in your specs.

Pass reference not options

---

lib/lhs/concerns/autoload_records.rb
lib/lhs/version.rb

The issue i faced during the update of `LHS` for `location_app` (some content was stripped on purpose):
```ruby
class DataLayer
class ListType
def build
if favorites?
'Favorites'
end
end
end
end
```
such file will be loaded automatically when there is the following class: `class Favorite < LHS::Record; end`
This PR changes the regexp to more restrict and might match only the whole word(s).
P.S. Not sure how to test this behaviour since the file i put inside `spec/dummy/app/models` will be loaded when tests are executed.

Fix autoloading of inheriting records

---

lib/lhs/concerns/autoload_records.rb
lib/lhs/version.rb
spec/dummy/app/models/concerns/dummy_customer/some_concern.rb
spec/dummy/app/models/dummy_customer.rb

some applications were showing weird behavior when using concerns for lhs records. 
e.g. causing 
```
TypeError:
superclass mismatch for class Place
```
Turns out that was because autoloading was autoloading those concerns, even though they are not lhs's business. ruby/rails takes care of autoloading them when loading the original records.
This PR fixes that issue. Unfortunately there was no way of adding a test for that (i've tried) but that issue has been described also by Dima here: https://github.com/local-ch/lhs/pull/397

prevent autoloading concerns

---

lib/lhs/collection.rb
lib/lhs/concerns/collection/internal_collection.rb
lib/lhs/concerns/record/request.rb
lib/lhs/version.rb
spec/record/includes_missing_spec.rb

This fixes an edge case where we include via 2 levels and the second level is missing.
```
NoMethodError:
undefined method `deep_merge' for nil:NilClass
```
https://rollbar.com/local.ch/opm/items/98256/

Fix loading missing includes

---

lib/lhs/concerns/collection/internal_collection.rb
lib/lhs/concerns/data/extend.rb
lib/lhs/concerns/record/request.rb
lib/lhs/version.rb
spec/record/compact_spec.rb
spec/record/includes_after_expansion_spec.rb
spec/record/request_spec.rb

When performing includes via multiple levels, .e.g.
```ruby
User.includes(places: :contracts)
```
LHS had problems to continue including nested includes, when there were unexpanded links in between, like places in this example, as `users/id/places` returns just a list of unexpanded place links.
This PR makes sure that LHS expands loaded links before continuing with includes.

Expand included links

---

lib/lhs/concerns/item/save.rb
lib/lhs/version.rb
spec/record/create_spec.rb

We already use `followlocation` option in `lhc` when we want to follow the redirects: https://github.com/local-ch/lhc/blob/master/README.md#follow-redirects
This PR adds the changes that `lhs` takes into account this option when it's going to follow the `Location` header in the response.
Only minor release since the default behaviour hasn't changed.

Do not follow Location header when followlocation option is set to false

---

lib/lhs/interceptors/auto_oauth/interceptor.rb
lib/lhs/version.rb
spec/auto_oauth_spec.rb
spec/dummy/app/controllers/automatic_authentication_controller.rb
spec/dummy/config/routes.rb

_PATCH_
Allows to use auth options which takes precedence over auto auth.
https://github.com/local-ch/lhs#automatic-authentication-oauth
```ruby
Record.options(auth: {. bearer: 'ACCESS_TOKEN'}).find(12345)
```

Fix auth options precedence for auto auth

---

lhs.gemspec
lib/lhs/concerns/item/save.rb
lib/lhs/version.rb
spec/item/save_spec.rb

The method `save` might be used to update existing entity, in such case, sometimes, another HTTP verb is needed.
This PR adds possibility to override default `POST` method by chaining `save` with `options` like:
`Entity.options(method: :put).save`

Add possibility to override HTTP request's method when chaining save with options.
