- lib/lhs/concerns/service/request.rb
- spec/service/includes_spec.rb
> ! fix single level includes option forwarding

- docs/services.md
- lib/lhs/concerns/service/endpoints.rb
- lib/lhs/data.rb
- spec/service/mapping_spec.rb
Allows mappings based on Service definitions also for nested data.
> Mappings for nested data

- lib/lhs/concerns/item/save.rb
- lib/lhs/concerns/item/update.rb
- lib/lhs/data.rb
- lib/lhs/proxy.rb
- spec/data/merge_spec.rb
- spec/proxy/load_spec.rb
Fix https://github.com/local-ch/lhs/issues/43
> ! fix load! merging data

- lib/lhs/collection.rb
- lib/lhs/concerns/service/all.rb
- spec/service/all_spec.rb
Dear reviewer, please pay a little bit more attention this time.
> ! devision by zero -.-

- lib/lhs/collection.rb
- lib/lhs/concerns/service/request.rb
- lib/lhs/item.rb
- spec/collection/delegate_spec.rb
- spec/item/delegate_spec.rb
- spec/item/destroy_spec.rb
- Fixes https://github.com/local-ch/lhs/issues/30
- Fixes destroy in combination with includes
> ! fix destroy with includes and delegates for item and collection

- lib/lhs/errors.rb
- spec/item/save_errors_spec.rb
https://github.com/local-ch/lhs/issues/48
> Handle 2 format of error messages

- lib/lhs/concerns/service/request.rb
- spec/service/includes_spec.rb
fixes https://github.com/local-ch/lhs/issues/46 & https://github.com/local-ch/lhs/issues/49
> ! skip empty includes

- lib/lhs/collection.rb
- lib/lhs/concerns/item/validation.rb
- lib/lhs/concerns/service/all.rb
- lib/lhs/concerns/service/batch.rb
- lib/lhs/concerns/service/request.rb
- lib/lhs/data.rb
- lib/lhs/item.rb
- lib/lhs/proxy.rb
- spec/item/internal_data_structure_spec.rb
- spec/item/setter_spec.rb
Improve internal data structure by sticking to symbols always!
> ! consistent internal data

- lib/lhs/data.rb
- spec/item/internal_data_structure_spec.rb
Handle the ActionController::Parameters case as its not really a Hash.
> ! internal data structure in case of building

- docs/services.md
- lib/lhs/concerns/service/includes.rb
- lib/lhs/concerns/service/request.rb
- spec/service/includes_spec.rb
E.g
```
Feedback.includes(:entry, :user)
Feedback.includes([:entry, :user])
Feedback.includes(campaign: [:entry, :user])
```
> Support array of includes

- docs/items.md
- docs/services.md
- lib/lhs/concerns/item/destroy.rb
- lib/lhs/concerns/item/save.rb
- lib/lhs/concerns/item/update.rb
- lib/lhs/concerns/item/validation.rb
- lib/lhs/concerns/service/all.rb
- lib/lhs/concerns/service/batch.rb
- lib/lhs/concerns/service/build.rb
- lib/lhs/concerns/service/create.rb
- lib/lhs/concerns/service/endpoints.rb
- lib/lhs/concerns/service/find.rb
- lib/lhs/concerns/service/find_by.rb
- lib/lhs/concerns/service/includes.rb
- lib/lhs/concerns/service/mapping.rb
- lib/lhs/concerns/service/request.rb
- lib/lhs/concerns/service/where.rb
- lib/lhs/data.rb
- lib/lhs/proxy.rb
- lib/lhs/service.rb
- spec/service/endpoint_options_spec.rb
- spec/service/endpoints_spec.rb
- spec/service/new_spec.rb
- spec/support/cleanup_services.rb
https://github.com/local-ch/lhs/issues/56
> Initalize with new

- lib/lhs/item.rb
- spec/data/item_spec.rb
Fixes https://github.com/local-ch/lhs/issues/70
> ! different formats for automated date time parsing

- README.md
- lib/lhs/record.rb
- spec/record/new_spec.rb
> + Use defined setters in initalizer

- README.md
- lib/lhs/collection.rb
- lib/lhs/concerns/item/destroy.rb
- lib/lhs/concerns/item/save.rb
- lib/lhs/concerns/item/update.rb
- lib/lhs/concerns/item/validation.rb
- lib/lhs/concerns/record/all.rb
- lib/lhs/concerns/record/batch.rb
- lib/lhs/concerns/record/configuration.rb
- lib/lhs/concerns/record/create.rb
- lib/lhs/concerns/record/endpoints.rb
- lib/lhs/concerns/record/find.rb
- lib/lhs/concerns/record/find_by.rb
- lib/lhs/concerns/record/where.rb
- lib/lhs/data.rb
- lib/lhs/endpoint.rb
- lib/lhs/proxy.rb
- lib/lhs/record.rb
- spec/collection/configurable_spec.rb
- spec/data/collection_spec.rb
- spec/data/raw_spec.rb
- spec/data/select_spec.rb
- Adds configuration ability to each LHS:Record (see added documentation)
- This one allows to use endpoints with different keys for pagination (like search)
> + configurable endpoints

- lib/lhs.rb
LHS was also preloading other rails classes which was clashing!!!
> ! fix autoloading

- lib/lhs/concerns/collection/internal_collection.rb
- spec/record/cast_nested_data_spec.rb
Fixes nested data casting in case of collections.
> ! nested data casting in collections

- lib/lhs/concerns/record/request.rb
- spec/record/includes_spec.rb
Fixes the extension of nested `items` while including nested resources
> ! extend base items with collections

- lib/lhs/item.rb
- spec/item/accessors_spec.rb
~ allow snake-style access to data delivered in camel case.
> Ruby Style Additional Data Accessors

- README.md
- lib/lhs/errors.rb
- lib/lhs/item.rb
- spec/item/add_error_spec.rb
- spec/record/create_spec.rb
In case you want to add custom validation errors to an instance of LHS::Record:
```ruby
user.errors.add(:name, 'The name you provided is not valid.')
```
> Item#errors.add

- README.md
> Docs: Paragraph for automatic detection of collections and how to configure it

- lib/lhs/collection.rb
- lib/lhs/concerns/proxy/accessors.rb
- lib/lhs/item.rb
- lib/lhs/proxy.rb
- spec/collection/accessors_spec.rb
```ruby
class Record < LHS::Record
endpoint ':datastore/records`'
end
```
Response:
```json
{
"items":  [{ "name": "Steve" }],
"extra":  "extra",
"total":  1
}
```
```ruby
Record.where.extra
```
```ruby
Record.where.extra
```
> Accessors in collection

- README.md
[WebMock](https://github.com/bblimke/webmock)! 
Best practice is to let LHS fetch your records and Webmock to stub/mock endpoints responses. 
This follows the [Black Box Testing](https://en.wikipedia.org/wiki/Black-box_testing) approach and prevents you from building up constraints to LHS' internal structures/mechanisms, which will break when we change internal things.
LHS provides interfaces that result in HTTP requests, this is what you should test.
```ruby
let(:contracts) do
[
{number: '1'},
{number: '2'},
{number: '3'}
]
end
before(:each) do
stub_request(:get, "http://datastore/user/:id/contracts")
.to_return(
body: {
items: contracts,
limit: 10,
total: contracts.length,
offset: 0
}.to_json
)
end
it 'displays contracts' do
visit 'contracts'
contracts.each do |contract|
expect(page).to …
```
> + how to test

- lib/lhs/concerns/record/request.rb
- spec/concerns/record/request_spec.rb
- spec/record/includes_all_spec.rb
Fixes https://github.com/local-ch/lhs/issues/217
> Fix `includes_all` for links with get params for pagination (like limit & offset)

- lhs.gemspec
- lib/lhs.rb
- lib/lhs/concerns/record/request.rb
- lib/lhs/concerns/record/request_cycle_cache/interceptor.rb
- lib/lhs/errors/base.rb
_PATCH_
Fixes non-rails consumers, like the command line tool we are working on.
> Fix non rails consumers

- lib/lhs/item.rb
- spec/item/map_spec.rb
Fixes: https://github.com/local-ch/lhs/issues/254
> ! map on items

- .rubocop.yml
- lhs.gemspec
- lib/lhs/concerns/record/chainable.rb
- lib/lhs/concerns/record/find.rb
- lib/lhs/concerns/record/find_by.rb
- lib/lhs/concerns/record/request.rb
- spec/record/ignore_errors_spec.rb
_PATCH_
As written in the docs. Ignored errors should always return nil.
https://github.com/local-ch/lhs#error-handling-with-chains
> Ensure ignored errors are always returning nil

- lib/lhs/concerns/record/request.rb
- spec/record/ignore_errors_spec.rb
> Fix `ignore` return nil on successful response

- lhs.gemspec
- lib/lhs/version.rb
Updates to fixed version of LHC (https://github.com/local-ch/lhc/releases/tag/v7.0.1)
> ! bump lhc

- lib/lhs/concerns/record/request_cycle_cache/interceptor.rb
- lib/lhs/version.rb
method signature of `before_request` changed
> necessary changes to be compatible with lhs 8.0.0

- lhs.gemspec
- lib/lhs/concerns/record/chainable.rb
- lib/lhs/concerns/record/request.rb
- lib/lhs/version.rb
- spec/record/handle_includes_errors_spec.rb
> Fix error handling

- lib/lhs/concerns/record/request.rb
- lib/lhs/version.rb
- spec/record/includes_all_spec.rb
…items without linked resources
> Handle items without linked resources

- lib/lhs/concerns/record/request.rb
- spec/record/includes_spec.rb
_PATCH_
LHS was not able to merge a Hash (collection without `item_key`) with an array.
This case is also supported and fixed by LHS
> Fix Include and merge array with hash

- lhs.gemspec
- lib/lhs/concerns/item/save.rb
- lib/lhs/concerns/item/update.rb
- lib/lhs/concerns/item/validation.rb
- lib/lhs/version.rb
- spec/record/endpoint_options_spec.rb
- spec/record/options_spec.rb
As LHC raises now when you explicitly set certain headers. we have to adapt LHS, too
> Make it compatible with latest lhc

- lib/lhs/concerns/record/merge.rb
- lib/lhs/record.rb
- lib/lhs/version.rb
- spec/record/force_merge_spec.rb
_MINOR_
Adds `merge`, `merge!`, `deep_merge` and `deep_merge!` to LHS
> Merge all the things

- lib/lhs/concerns/record/request.rb
- lib/lhs/version.rb
- spec/record/includes_all_spec.rb
This PR fixes a case where included links with pagination parameters where internally having not symbolized keys what made pagination fail.
> Fix internal data structure, ensure to have symbolized keys

- README.md
to update and partial_update...
> Adding documentation for how to pass explicit options

- Gemfile
- lhs.gemspec
- lib/lhs/test/stub.rb
- spec/stubs/all_spec.rb
patch to allow LHS.stub.all without webmock request options.
> Fix stub all without options

- lib/lhs/concerns/collection/internal_collection.rb
- lib/lhs/version.rb
- spec/record/compact_spec.rb
- spec/record/references_spec.rb
https://jira.localsearch.ch/browse/pro-1272
- Add specs to prevent regressions and for faster bugfixing
> PRO-1272 Bugfix: Fix Broken Type Mapping

- .github/workflows/rubocop.yml
- .github/workflows/test-active-support-5.yml
- .github/workflows/test.yml
- spec/dummy/app/controllers/request_cycle_cache_controller.rb
- spec/dummy/config/initializers/lhs.rb
- spec/dummy/config/routes.rb
- spec/request_cycle_cache_spec.rb
Replace deprecated github actions and fix tests.
> Replace deprecated github actions and fix tests.

- lhs.gemspec
- lib/lhs/version.rb
Bumps lhc version and because that could introduce lhc major version 15, also increase LHS's version.
> Allow higher lhc versions

- lib/lhs/concerns/record/request.rb
- lib/lhs/version.rb
- spec/record/includes_after_expansion_spec.rb
I noticed that in case when the data is a collection of items then we couldn't expand included resources correctly. This PR is supposed to fix this behavior.
> Fix expand of data for collections.
